-- Add missing character fields to support full character profiles
-- This migration adds all the necessary columns for displaying complete character information

ALTER TABLE characters ADD COLUMN IF NOT EXISTS hair_color VARCHAR(255) DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS eye_color VARCHAR(255) DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS beard_style VARCHAR(255) DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS special_features TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS height INT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS weight INT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS body_type VARCHAR(255) DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS physical_features TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS phobias TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS character_values TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS education TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS scientific_profile TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS research_motivation TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS military_experience TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS military_rank VARCHAR(255) DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS military_join_reason TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS backstory TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS zone_motivation TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS character_goals TEXT DEFAULT NULL;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS discord_id VARCHAR(255) DEFAULT NULL;
